const ActionTypes = {
    FETCH_HEALTH: 'FETCH_HEALTH',
    FETCH_ENV: 'FETCH_ENV',
    FETCH_METRICS: 'FETCH_METRICS',
    FETCH_METRIC_DETAIL: 'FETCH_METRIC_DETAIL',
    SET_METRIC_DETAIL_LAYOUT: 'SET_METRIC_DETAIL_LAYOUT'
}

export default ActionTypes;
